### ISSUE TITLE
[Bug]: Create Space - Username Cannot Have a '@'

### ISSUE THREAD

**Issue by PureMunky** [cloudfoundry/cf-k8s-controllers#280]
### What happened?

When creating a new space I was presented the error below.

```
2021-11-23T12:02:54.340Z    ERROR    Role Handler    Failed to create role    {"Role Type": "organization_user", "Space": "", "User": "pcorbett@vmware.com", "error": "failed to assign user \"pcorbett@vmware.com\" to role \"organization_user\": RoleBinding.rbac.authorization.k8s.io \"cf-0d487f154765e3c887f774908fdbde46f849cf0c0ef41fa20c353c1811bd6595\" is invalid: metadata.labels: Invalid value: \"pcorbett@vmware.com\": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9[][-A-Za-z0-9_.[]*)?[A-Za-z0-9[])?')"}
github.com/gorilla/mux.(*Router).ServeHTTP
    /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210
net/http.serverHandler.ServeHTTP
    /usr/local/go/src/net/http/server.go:2878
net/http.(*conn).serve
    /usr/local/go/src/net/http/server.go:1929
```

### What you expected to happen

I expected to have a new Space created and no error displayed.

### Acceptance Criteria

GIVEN I have the latest API Shim installed on my cluster
AND the latest CLI installed
WHEN I create a new space using `cf create-space <spaceName>`
THEN I see a new space created and no error message.

### How to reproduce it (as minimally and precisely as possible)

1. Running on GKE
2. `cf login`, selected my GKE config
3. Created a brand new org `cf create-org NewOrg`
4. Created a brand new space `cf create-space NewSpace`

### Anything else we need to know?

The space was created but the error message makes it look like it wasn't.

### Environment

Revision of codebase: https://github.com/cloudfoundry/cf-k8s-controllers/commit/5f7028ca5ce6bbc9acde143cc60950c2909b3e64
Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1802", GitCommit:"d464a255a4acb8dca1e0914586f4f5085681fb51", GitTreeState:"clean", BuildDate:"2021-10-21T21:43:23Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud provider or hardware configuration: GKE

**Comment by gcapizzi** [comment]
This is due to us trying to store the username as a [label attached to the `RoleBinding`](https://github.com/cloudfoundry/cf-k8s-controllers/blob/a337d07b63e88e3ed63e2eb57907c77f51c8716c/api/repositories/role_repository.go#L108):
```go
roleBinding := rbacv1.RoleBinding{
    ObjectMeta: metav1.ObjectMeta{
        // ...
        Labels: map[string]string{
            RoleGuidLabel: role.GUID,
            RoleUserLabel: role.User,
            RoleTypeLabel: role.Type,
        },
        // ...
    },
    // ...
}
```

Label values are [very restricted in which characters they can use](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set), so they are just not suited for storing usernames.

These labels might be useful in the future to implement other operations on roles (e.g. listing), but they are unused at the moment, so I'm going to get rid of them. The GUID label will be needed to implement `DELETE`s, and GUIDs are always valid label values, so it can stay.

Shall we decide to implement listing one day, here are some ideas that came up with the team:
* we could list all `RoleBinding`s with the privileged clients and then filter them ourselves, similarly to what we do with orgs and spaces;
* we could use caches to make that more efficient;
* we could encode usernames to make them label-friendly, e.g. using hashing.

**Comment by gcapizzi** [comment]
Trying to use a username with `@` in it in the tests fails even after removing the labels:
```
RoleBinding.rbac.authorization.k8s.io "foo" is invalid: subjects[0].name: Invalid value: "myuser@example.com": a DNS-1123 subdomain must consist of lower case al
phanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-
9]*[a-z0-9])?)*')
```
This seems to suggest that `@`s are not admitted in subject names, which is weird as it contradicts these [GCP docs](https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#role) for example. This might be a difference between `envtest` and GCP, which means we might not be able to add a regression test for this fix.
