### ISSUE TITLE
[Chore] Enable the dupl linter

### ISSUE THREAD

**Issue by mnitchev** [cloudfoundry/cf-k8s-controllers#291]
We recently enabled golangci-lint, but only use the default linters. The dupl linter checks for duplication in our code. Since we ran it and found that there are a few places where we have a lot of duplications, we feel that this might be a useful thing to check. [Link to the linter](https://github.com/mibk/dupl

**Comment by danail-branekov** [comment]
I tried enabling the dupl linter and got lots of warnings. After looking at them, I could classify duplications like this:

## API duplications

### Rest handlers boilerplate
Those code duplications are caused by the huge amount of boilerplate around request handling, e.g.:
1. Get the authInfo from the request + its error handling
2. Talk to the underlying repository + related error handling
3. send the result from the repo to the presenter + related error handling


### Repositories duplications
Repositories implement similar patterns:
* They all have some sort of `Get` and `List` methods
* Those methods always talk to the k8s client by calling its `Get` or `List`
* Format the result from the k8s client and return it

## Controllers duplications
Those duplications are mostly around subnamespaces which makes sense. Orgs and spaces are backed up by the same subnamespace anchor, hence the orgs implementation is quite similar to the spaces one. 

## Error case tests
This might be a natural consequence of the duplications listed above. Generally, similar handlers code requires similar test code, hence the duplication


In order to address the duplications we could:
* For rest handlers we could extract an abstract rest handler that gets the authinfo from the context and use template methods (or even strategies) to proceed with the thing the handler is expected to do. For example, a `GetXXX` handler could have functions injected during wiring one talking to the repo and another talking to the presenter
* For controllers, I guess introducing an org/space custom resources would make the controllers duplications similar to the rest api handlers ones, we could tackle them in a similar manner
* For the errors tests - I guess the actions above would solve most of them

**However**, I do believe that the refactoring above would make the code quite unreadable (and maybe hard to maintain) so I would probably limit the refactoring down to just extracting the authinfo in a wrapper. For the rest of the duplications, we could probably turn the linter off. But if we turn the linter off for those packages, does it make sense to enable it all?
