### ISSUE TITLE
[Feature]: CF-K8s Developer can see CFRoutes provide a destination status

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cf-k8s-controllers#376]
### Blockers/Dependencies

* Related to injecting `PORT`/`VCAP_APP_PORT` vars into an App's environment: https://github.com/cloudfoundry/cf-k8s-controllers/issues/331

### Background

**As an** cf-k8s developer
**I want** to see the port on the CFRoute status
**So that** I can implement #331 

### Acceptance Criteria

**GIVEN** I have an http CFRoute
**WHEN I** `cf map-route` the Route to an App
**THEN I** see that `Status` of the `CFRoute` matches the `targetPort` on the resulting `Service`

For example, CFRoute could resemble the following, with `destinations` reflected in the status of the route:
```yaml
apiVersion: networking.cloudfoundry.org/v1alpha1
kind: CFRoute
metadata:
  finalizers:
    - cfRoute.networking.cloudfoundry.org
  generation: 1
  labels:
    networking.cloudfoundry.org/domain-guid: 5b5032ab-7fc8-4da5-b853-821fd1879201
    networking.cloudfoundry.org/route-guid: 84afc0f2-3dc2-4709-9fc8-8340be584a43
  managedFields:
  name: 84afc0f2-3dc2-4709-9fc8-8340be584a43
  namespace: cf
  resourceVersion: "1574139"
  uid: 319d7e46-4bc7-48c4-a7eb-95dd90ba35b0
spec:
  destinations:
    - appRef:
        name: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
      guid: 8ad77ef4-53d5-117a-b640-0ae227a13f35
      port: 9001
      processType: web
      protocol: http1
  domainRef:
    name: 5b5032ab-7fc8-4da5-b853-821fd1879201
  host: my-host
  path: /
  protocol: http
status:
  conditions:
    - lastTransitionTime: "2021-12-20T18:49:04Z"
      message: Valid CFRoute
      reason: Valid
      status: "True"
      type: Valid
  currentStatus: valid
  description: Valid CFRoute
  fqdn: my-host.example.org
  uri: my-host.example.org/
  destinations:
    - appRef:
        name: 14dcda7d-1fa1-4a91-b437-fbdba20e8c5a
      guid: 8ad77ef4-53d5-117a-b640-0ae227a13f35
      port: 9001 # <--------------  This is taken from the `CFRoute` spec
      processType: web
      protocol: http1
```

---

### Dev Notes

Cloud Controller code:

* https://github.com/cloudfoundry/cloud_controller_ng/blob/ed09b45936879975e9784927431cc5387e1221d4/app/models/runtime/process_model.rb#L566-L584
* https://github.com/cloudfoundry/cloud_controller_ng/blob/ed09b45936879975e9784927431cc5387e1221d4/lib/cloud_controller/diego/buildpack/desired_lrp_builder.rb#L105-L111

**Comment by julian-hj** [comment]
Pairing on this with @acosta11, we weren't able to find a use case where the port is set on the droplet in a buildpack app. We speculate that that's because most buildpack apps will respect the $PORT environment variable, and therefore don't want to declare a port.

Here's what the status looks like on our CFBuild CR after pushing a ruby app:

```
  status:
    conditions:
      ...
    droplet:
      ports: []
      processTypes:
      - command: bundle exec rackup --env RACK_ENV=production -p "${PORT:-9292}"
        type: web
      ...
```

Note that the actual port will default to 9292, but there's no indication of that on the droplet.

Node apps are similar:

```
    droplet:
      ports: []
      processTypes:
      - command: node server.js
```

We are thinking we should split this story, and just do the part where we copy the destination into the status of the route so that we can use that information. We can make a separate story for getting the port from different places to do later.

**Comment by julian-hj** [comment]
We split this story and moved most of the hard parts to #388 since we aren't certain when/if we will need to support non-8080 http ports.

**Comment by Birdrock** [comment]
@tcdowney This appears to work, but I'm curious about how we intend the information flow to be. Currently the Route `Status` is set based on the route `Spec`, rather than the resulting `Service.Spec`. Should the Route `Status` be the result of the reconciled `Service` instead of a carbon copy of the Route `Spec`?

**Comment by tcdowney** [comment]
> Should the Route Status be the result of the reconciled Service instead of a carbon copy of the Route Spec?

Yeah 👍 

I think we deprioritized this use case for now, but the reason for doing this originally was:

The port for a destination is optional in the V3 APIs (if it's not present we end up using either the port on the `CFProcess` or defaulting to `8080`) so if we want to maintain that behavior it needs to be optional here. That said, we still need a way to discover what port was actually used on the `Service` (primarily for injecting the `PORT` and `VCAP_APP_PORT` env system env vars) so we figured we'd propagate that over to the `Status`.
