### ISSUE TITLE
[Feature]: Validate against overlapping domains

### ISSUE THREAD

**Issue by Birdrock** [cloudfoundry/cf-k8s-controllers#662]
### Blockers/Dependencies

This depends upon CFDomains being namespaced resources.

### Background

**As a** platform operator
**I want** validation to prevent overlapping domains
**So that** avoid collisions

### Acceptance Criteria

**GIVEN** An existing CFDomain
**WHEN I** attempt to create a new CFDomain with an overlapping same domain
**THEN I** see the CFDomain is rejected

### Dev Notes

Example:
* New domain `foo.example.com` is invalid if there is a domain `bar.foo.example.com`.
* New domain `bar.foo.example.com` is invalid if there is a domain `foo.example.com`.

**Comment by gnovv** [comment]
In order to get kubebuilder command to work with the new monorepo structure, we had to make a couple changes:

1.  Update the PROJECT file in controllers/ to add the subdirectory `controllers` in this line:
```
repo: code.cloudfoundry.org/cf-k8s-controllers/controllers
```
2. Copy the Makefile into the `controllers/` directory temporarily and add the target below:
```
generate: install-controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./..."
```
3. Run the kubebuilder command: (this is for a validating webhook)
```
kubebuilder create webhook --group networking --version v1alpha1 --kind CFDomain --programmatic-validation

```
4. Run the make-manifests target in the root directory

```
cd ..
make manifests-controllers
```
5. Delete the extra Makefile
```
rm -rf controllers/Makefile
```
